modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"

[[mods]]
modId="inventory_crafter"
version="${file.jarVersion}"
displayName="Inventory Crafter"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
#logoFile="inventory_crafter.png"
#credits="Joe Mama"
authors="LegoMaster3650"
description='''
Gives you a portable crafting table button/keybind if you have a crafting table item
'''

[[dependencies.inventory_crafter]]
	modId="forge"
	mandatory=true
	versionRange="[40,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.inventory_crafter]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.18.2,1.19)"
	ordering="NONE"
	side="BOTH"

[modproperties.inventory_crafter]
	catalogueItemIcon="minecraft:crafting_table"